### ISSUE TITLE
Suggestion: hdmi to csi-2 for video capture?

### ISSUE THREAD

**Issue by battletux** [PrawnMan/HdmiPi-Streaming#1]
Hi, have you seen the pikvm project? https://github.com/pikvm/pikvm#diy-getting-started

They suggest using a hdmi to csi-2 bridge for capture of hdmi. It is lower latency and allows for 1080p resolution. It may allow for a better capture.

**Comment by PrawnMan** [comment]
Sorry for the slow response! I've seen that project, infact my original idea was to use the CSI Interface. The reason I decided to go the USB HDMI capture route is because the USB devices are generally more readily available and inexpensive compared to the CSI bridge. However, I do have plans to get a CSI bridge and add a writeup for using that to stream!
